### ISSUE TITLE
Sections not disappearing

### ISSUE THREAD

**Issue by ghost** [Leveton/MELCoda#1]
Hi Michael, thanks for the good work. Unfortunately both the side-bar and book-sections still appear in the code. As suggested by JFM (as below) updated the javascript file but still the sections do appear. Pls check and fix.

To make the book section disappear as described in the text, the second row in hideSections.js needs to changed from:
styleTag.textContent = 'div#sidebar, .after-post.widget-area {display:none;}';
to:
styleTag.textContent = 'div#sidebar, .footer-widgets {display:none;}';

**Comment by Leveton** [comment]
@stargana ok I pushed your change but I didn't see the sidebar or book sections before or after the change.  Which device are you running this on?

**Comment by ghost** [comment]
Thanks. I'm running it in iPhone 6. Even after making the JavaScript changes, the sections were appearing. So I felt it needs to be fixed in the code.

**Comment by bwoodruff** [comment]
@Leveton I can't seem to get any JavaScript to run from either the getPosts.js or hideSections.js files. I changed the contents of both to:
`window.location = "http://google.com/"`

This does not execute at all. I'm never taken to Google.
